
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 16 20:42:46 CET 2014
//----------------------------------------------------

package rs.etf.markic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 26;
  public static final int CONST = 3;
  public static final int STRCONST = 18;
  public static final int NOTEQUAL = 31;
  public static final int LPAREN = 22;
  public static final int GREATER = 32;
  public static final int SEMI = 21;
  public static final int MINUS = 37;
  public static final int LESS = 34;
  public static final int RPAREN = 23;
  public static final int AND = 29;
  public static final int LESSEQUAL = 35;
  public static final int OR = 28;
  public static final int COMMA = 20;
  public static final int CLASS = 4;
  public static final int INC = 38;
  public static final int DIV = 41;
  public static final int PLUS = 36;
  public static final int ASSIGN = 43;
  public static final int IF = 6;
  public static final int DOT = 19;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 27;
  public static final int EQUAL = 30;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 40;
  public static final int MOD = 42;
  public static final int NUMBER = 15;
  public static final int BREAK = 11;
  public static final int IDENT = 14;
  public static final int VOID = 44;
  public static final int GREATEREQUAL = 33;
  public static final int LBRACE = 24;
  public static final int ELSE = 7;
  public static final int READ = 9;
  public static final int CHARCONST = 16;
  public static final int WHILE = 8;
  public static final int RBRACE = 25;
  public static final int BOOLCONST = 17;
  public static final int EXTENDS = 5;
  public static final int DEC = 39;
  public static final int PRINT = 10;
}

